S_FOOD/Controllers/AdminBuaAnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class AdminBuaAnController : Controller
    {
        DBSfoodDataContext data = new DBSfoodDataContext();
        // GET: AdminBuaAn
        public ActionResult Index()
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            List<LOAIBUAAN> all = data.LOAIBUAANs.ToList();
            return View(all);
        }

        // GET: AdminBuaAn/Details/5
        public ActionResult Details(int id)
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }

            LOAIBUAAN kv = data.LOAIBUAANs.SingleOrDefault(i => i.ID_Loai == id);
            return View(kv);
        }

        // GET: AdminBuaAn/Create
        public ActionResult Create()
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            return View();
        }

        // POST: AdminBuaAn/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection, LOAIBUAAN loai)
        {
            var ten = collection["TenBuaAn"];
            loai.TenLoai = ten;
            data.LOAIBUAANs.InsertOnSubmit(loai);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }

        // GET: AdminBuaAn/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            LOAIBUAAN kv = data.LOAIBUAANs.SingleOrDefault(i => i.ID_Loai == id);
            return View(kv);
        }

        // POST: AdminBuaAn/Edit/5
        [HttpPost]
        public ActionResult Edit(LOAIBUAAN loai, FormCollection collection)
        {
            LOAIBUAAN l = data.LOAIBUAANs.SingleOrDefault(i => i.ID_Loai == loai.ID_Loai);
            l.TenLoai = loai.TenLoai;
            if (ModelState.IsValid)
            {

                UpdateModel(l);
                data.SubmitChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: AdminBuaAn/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            LOAIBUAAN kv = data.LOAIBUAANs.SingleOrDefault(n => n.ID_Loai == id);
            ViewBag.ID = kv.ID_Loai;
            if (kv == null)
            {

                return RedirectToAction("Index", "AdminVIP");
            }
            return View(kv);
        }

        // POST: AdminBuaAn/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            LOAIBUAAN kv = data.LOAIBUAANs.SingleOrDefault(i => i.ID_Loai == id);
            int countLoai = data.MONANs.Count(i => i.ID_Loai == id);
            if (countLoai > 0)
            {
                ViewBag.ErrorBody = string.Format("Không thể Xóa,  do Loại [{0}] đang có [{1}] món ăn.", kv.TenLoai, countLoai);
                List<LOAIBUAAN> all = data.LOAIBUAANs.ToList();
                return View("Index", all.ToList());
            }
            else
            if (ModelState.IsValid)
            {
                data.LOAIBUAANs.DeleteOnSubmit(kv);
                data.SubmitChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

S_FOOD/Controllers/DoanhThuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class DoanhThuController : Controller
    {
        DBSfoodDataContext data = new DBSfoodDataContext();       
        // GET: DoanhThu       
        public ActionResult Index()
        {            
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            CONGTACVIEN tk = (CONGTACVIEN)Session["TenTK_CTV"];
            var sum = from m in data.DOANHTHUs where m.MaTK_CTV == tk.MaTK_CTV select m;
            return View(sum);
        }

        public ActionResult DoanhThuAll()
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            List<DOANHTHU> all = data.DOANHTHUs.ToList();
            return View(all);
        }

        public ActionResult Tinh()
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Tinh(FormCollection collection, DOANHTHU dt)
        {

            var gt = collection["ID_ChiecKhau"];
            ViewBag.MessageFail = string.Empty;          
            if (!string.IsNullOrEmpty(ViewBag.MessageFail))
            {
                return View();

            }
            CONGTACVIEN tk = (CONGTACVIEN)Session["TenTK_CTV"];
            decimal sum = 0;  
            dt.MaTK_CTV = tk.MaTK_CTV;
            sum = Convert.ToDecimal(data.f_tongdt(tk.MaTK_CTV));
            dt.TongDoanhThu = sum;
            decimal tck = 0;
            tck = sum * Decimal.Parse(gt);
            dt.TienChiecKhau = tck;
           

            if (ModelState.IsValid)
            {
                data.DOANHTHUs.InsertOnSubmit(dt);
                try
                {
                    dt.Thang = DateTime.Now;
                    data.SubmitChanges();
                }
                catch (Exception ex)
                {
                    if (ex.Message.Contains("Violation of PRIMARY KEY constraint"))
                    {
                        ViewBag.MessageFail = string.Format("Doanh thu tháng {0} đã tồn tại, nếu muốn thay đổi, Vui lòng CẬP NHẬT.", dt.Thang);
                    }
                    else
                    {
                        ViewBag.ErrorBody = ex.ToString();
                    }
                    return View();
                }
            }

            ViewBag.MessageSuccess = "Tính doanh thu tháng : [" + dt.Thang + "] thành công";
            return View();

        }

        // GET: DoanhThu/Details/5
        
        // GET: DoanhThu/Edit/5
        public ActionResult Edit(int id)
        {
            DOANHTHU kv = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == id);
            return View(kv);
        
        }



        // POST: DoanhThu/Edit/5
        [HttpPost]
        public ActionResult Edit(DOANHTHU dt, FormCollection collection)
        {
        
            DOANHTHU doanhthu = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == dt.MaTK_CTV);
            var gt = collection["ID_ChiecKhau"];
            dt.TienChiecKhau = doanhthu.TongDoanhThu * Convert.ToDecimal(gt);
            doanhthu.TienChiecKhau = dt.TienChiecKhau;
            doanhthu.Thang = DateTime.Now;
            if (ModelState.IsValid)
            {

                UpdateModel(doanhthu);
                data.SubmitChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: DoanhThu/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DoanhThu/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult AdminEdit(int id)
        {
            DOANHTHU kv = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == id);
            return View(kv);

        }

        // POST: DoanhThu/Edit/5
        [HttpPost]
        public ActionResult AdminEdit(DOANHTHU dt, FormCollection collection)
        {
            DOANHTHU doanhthu = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == dt.MaTK_CTV);
            var gt = collection["ID_ChiecKhau"];
            dt.TienChiecKhau = doanhthu.TongDoanhThu * Convert.ToDecimal(gt);
            doanhthu.TienChiecKhau = dt.TienChiecKhau;
            doanhthu.Thang = DateTime.Now;
            if (ModelState.IsValid)
            {

                UpdateModel(doanhthu);
                data.SubmitChanges();
            }
            return RedirectToAction("DoanhThuAll");
        }

        public ActionResult GiaTriCK(double ? id)
        {
            List<CHIECKHAU> all = data.CHIECKHAUs.ToList();
            if (id != null)
            {
                ViewBag.idLoai = id;
            }
            return PartialView(all);
        }
    }
}

S_FOOD/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Trang chủ Admin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="main-content">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span12">
                    <h4 class="title">
                        <span class="pull-left"><span class="text"><span class="line">QUẢN <strong>LÝ</strong></span></span></span>
                    </h4>
                    <div id="myCarousel" class="myCarousel carousel slide">
                        <div class="carousel-inner">
                            <div class="active item">
                                <ul class="thumbnails">
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","AdminCTV")"><img src="~/images/Admin/icon-ctv.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","AdminCTV")" class="price">Cộng tác viên </a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","AdminVIP")"><img src="~/images/Admin/icon-vip.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","AdminVIP")" class="price">Quảng cáo</a></p>

                                        </div>
                                    </li>

                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","AdminKhuVuc")"><img src="~/images/Admin/icon-khuvuc.gif" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","AdminKhuVuc")" class="price">Khu vực</a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","AdminBuaAn")"><img src="~/images/Admin/icon-loai.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","AdminBuaAn")" class="price">Loại bữa ăn</a></p>

                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","AdminChiecKhau")"><img src="~/images/Admin/icon-chieckhau.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"><a href="@Url.Action("Index","AdminChiecKhau")" class="price">Chiếc khấu</a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","AdminCaiDat")"><img src="~/images/Admin/icon-caidat.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"><a href="@Url.Action("Index","AdminCaiDat")" class="price">Cài đặt</a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("DoanhThuAll","DoanhThu")"><img src="~/images/Admin/icon-tien.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"><a href="@Url.Action("DoanhThuAll","DoanhThu")" class="price">Doanh thu</a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","AdminThongKe")"><img src="~/images/Admin/icon-thongke.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","AdminThongKe")" class="price">Thống kê </a></p>
                                        </div>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>