S_FOOD/Controllers/CTVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class CTVController : Controller
    {
        // GET: CTV
        public ActionResult Index()
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            return View();
        }

        // GET: CTV/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CTV/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CTV/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CTV/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CTV/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CTV/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CTV/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

S_FOOD/Controllers/CTVDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class CTVDonHangController : Controller
    {
        DBSfoodDataContext data = new DBSfoodDataContext();
        // GET: CTVDonHang
        public ActionResult Index()
        {
           
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            CONGTACVIEN tk = (CONGTACVIEN)Session["TenTK_CTV"];
            var monan = from m in data.DONHANGs where m.MONAN.MaTK_CTV == tk.MaTK_CTV where m.DATHANG.TinhTrangGiao == false select m;
            return View(monan);
        }

        // GET: CTVDonHang/Details/5
        public ActionResult Details(int id)
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            DONHANG dh = this.data.DONHANGs.FirstOrDefault(i => i.ID_DatHang == id);
            return View(dh);
        }

        // GET: CTVDonHang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CTVDonHang/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CTVDonHang/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            DATHANG ctv = data.DATHANGs.SingleOrDefault(i => i.ID_DatHang == id);
            return View(ctv);
        }

        // POST: CTVDonHang/Edit/5
        [HttpPost]
        public ActionResult Edit(DATHANG dh, FormCollection collection)
        {
            DATHANG ctv = data.DATHANGs.SingleOrDefault(i => i.ID_DatHang == dh.ID_DatHang);
            ctv.DaThanhToan = dh.DaThanhToan;
            ctv.TinhTrangGiao = dh.TinhTrangGiao;
            {
                UpdateModel(ctv);
                data.SubmitChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

S_FOOD/Controllers/CTVThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class CTVThongKeController : Controller
    {
        // GET: SFood
        DBSfoodDataContext data = new DBSfoodDataContext();
        public List<MONAN> MonAnBanChay(int count)
        {
            return data.MONANs.OrderByDescending(a => a.SoLuong).Take(count).ToList();

        }
        public ActionResult PV_ThongKeKhachHang()
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            CONGTACVIEN tk = (CONGTACVIEN)Session["TenTK_CTV"];
            var top = from m in data.V_Top5KhachHangs where m.MaTK_CTV == tk.MaTK_CTV select m;
            return PartialView(top);
        }

        public ActionResult PV_ThongKeMonAn()
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            CONGTACVIEN tk = (CONGTACVIEN)Session["TenTK_CTV"];
            var top = from m in data.V_Top5MonAns where m.MaTK_CTV == tk.MaTK_CTV select m;
            return PartialView(top);
        }
        // GET: CTVThongKe
        public ActionResult Index()
        {
                        
            return View();
        }

        // GET: CTVThongKe/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CTVThongKe/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CTVThongKe/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CTVThongKe/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CTVThongKe/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CTVThongKe/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CTVThongKe/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

S_FOOD/Controllers/DoanhThuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class DoanhThuController : Controller
    {
        DBSfoodDataContext data = new DBSfoodDataContext();       
        // GET: DoanhThu       
        public ActionResult Index()
        {            
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            CONGTACVIEN tk = (CONGTACVIEN)Session["TenTK_CTV"];
            var sum = from m in data.DOANHTHUs where m.MaTK_CTV == tk.MaTK_CTV select m;
            return View(sum);
        }

        public ActionResult DoanhThuAll()
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            List<DOANHTHU> all = data.DOANHTHUs.ToList();
            return View(all);
        }

        public ActionResult Tinh()
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Tinh(FormCollection collection, DOANHTHU dt)
        {

            var gt = collection["ID_ChiecKhau"];
            ViewBag.MessageFail = string.Empty;          
            if (!string.IsNullOrEmpty(ViewBag.MessageFail))
            {
                return View();

            }
            CONGTACVIEN tk = (CONGTACVIEN)Session["TenTK_CTV"];
            decimal sum = 0;  
            dt.MaTK_CTV = tk.MaTK_CTV;
            sum = Convert.ToDecimal(data.f_tongdt(tk.MaTK_CTV));
            dt.TongDoanhThu = sum;
            decimal tck = 0;
            tck = sum * Decimal.Parse(gt);
            dt.TienChiecKhau = tck;
           

            if (ModelState.IsValid)
            {
                data.DOANHTHUs.InsertOnSubmit(dt);
                try
                {
                    dt.Thang = DateTime.Now;
                    data.SubmitChanges();
                }
                catch (Exception ex)
                {
                    if (ex.Message.Contains("Violation of PRIMARY KEY constraint"))
                    {
                        ViewBag.MessageFail = string.Format("Doanh thu tháng {0} đã tồn tại, nếu muốn thay đổi, Vui lòng CẬP NHẬT.", dt.Thang);
                    }
                    else
                    {
                        ViewBag.ErrorBody = ex.ToString();
                    }
                    return View();
                }
            }

            ViewBag.MessageSuccess = "Tính doanh thu tháng : [" + dt.Thang + "] thành công";
            return View();

        }

        // GET: DoanhThu/Details/5
        
        // GET: DoanhThu/Edit/5
        public ActionResult Edit(int id)
        {
            DOANHTHU kv = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == id);
            return View(kv);
        
        }



        // POST: DoanhThu/Edit/5
        [HttpPost]
        public ActionResult Edit(DOANHTHU dt, FormCollection collection)
        {
        
            DOANHTHU doanhthu = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == dt.MaTK_CTV);
            var gt = collection["ID_ChiecKhau"];
            dt.TienChiecKhau = doanhthu.TongDoanhThu * Convert.ToDecimal(gt);
            doanhthu.TienChiecKhau = dt.TienChiecKhau;
            doanhthu.Thang = DateTime.Now;
            if (ModelState.IsValid)
            {

                UpdateModel(doanhthu);
                data.SubmitChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: DoanhThu/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DoanhThu/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult AdminEdit(int id)
        {
            DOANHTHU kv = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == id);
            return View(kv);

        }

        // POST: DoanhThu/Edit/5
        [HttpPost]
        public ActionResult AdminEdit(DOANHTHU dt, FormCollection collection)
        {
            DOANHTHU doanhthu = data.DOANHTHUs.SingleOrDefault(i => i.MaTK_CTV == dt.MaTK_CTV);
            var gt = collection["ID_ChiecKhau"];
            dt.TienChiecKhau = doanhthu.TongDoanhThu * Convert.ToDecimal(gt);
            doanhthu.TienChiecKhau = dt.TienChiecKhau;
            doanhthu.Thang = DateTime.Now;
            if (ModelState.IsValid)
            {

                UpdateModel(doanhthu);
                data.SubmitChanges();
            }
            return RedirectToAction("DoanhThuAll");
        }

        public ActionResult GiaTriCK(double ? id)
        {
            List<CHIECKHAU> all = data.CHIECKHAUs.ToList();
            if (id != null)
            {
                ViewBag.idLoai = id;
            }
            return PartialView(all);
        }
    }
}

S_FOOD/Views/CTV/Index.cshtml
@{
    ViewBag.Title = "Trang chủ Cộng tác viên";
    Layout = "~/Views/Shared/_LayoutCTV.cshtml";
}
@model IEnumerable<S_FOOD.Models.MONAN>
<section class="main-content">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span12">
                    <h4 class="title">
                        <span class="pull-left"><span class="text"><span class="line">QUẢN <strong>LÝ</strong></span></span></span>
                    </h4>
                    <div id="myCarousel" class="myCarousel carousel slide">
                        <div class="carousel-inner">
                            <div class="active item">
                                <ul class="thumbnails">
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","CTVMonAn")"><img src="~/images/CTV-Icon/icon-monan.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","CTVMonAn")" class="price">Món ăn </a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","CTVKhuyenMai")"><img src="~/images/Admin/icon-khuyenmai.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","CTVKhuyenMai")" class="price">Khuyến mại</a></p>

                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","CTVDonHang")"><img src="~/images/CTV-Icon/icon-donhang.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","CTVDonHang")" class="price">Đơn hàng </a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","DoanhThu")"><img src="~/images/CTV-Icon/icon-tien.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","DoanhThu")" class="price">Doanh thu </a></p>
                                        </div>
                                    </li>
                                    <li class="span3">
                                        <div class="product-box">
                                            <span class="sale_tag"></span>
                                            <p><a href="@Url.Action("Index","CTVThongKe")"><img src="~/images/CTV-Icon/icon-thongke.png" style="height:190px; width:400px" alt="" /></a></p>
                                            <p style="font-size:16px; font-weight:bold"> <a href="@Url.Action("Index","CTVThongKe")" class="price">Thống kê </a></p>
                                        </div>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>