S_FOOD/Controllers/AdminKhuyenMaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class AdminKhuyenMaiController : Controller
    {
        DBSfoodDataContext data = new DBSfoodDataContext();
        // GET: AdminKhuyenMai
        public ActionResult Index()
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            List<KhuyenMai> all = data.KhuyenMais.ToList();
            return View(all);           
        }

        // GET: AdminKhuyenMai/Details/5
        public ActionResult Details(string id)
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
           /* GiaDaGiam gia = new GiaDaGiam(id);
            decimal g = 0;
            g = gia.dGiaDaGiam;
            ViewBag.Gia = g;
            KHUYENMAI km = data.KHUYENMAIs.SingleOrDefault(i => i.ID_KhuyenMai == id);        */    
            return View();
        }

        // GET: AdminKhuyenMai/Create
        public ActionResult Create()
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            return View();
        }

        // POST: AdminKhuyenMai/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection, KhuyenMai km)
        {

            var giagiam = Convert.ToDouble(collection["GiaGiam"]);
            int monan = Convert.ToInt32(collection["IDMonAn"]);
            ViewBag.MessageFail = string.Empty;
            if (monan == 0)
            {
                ViewBag.MessageFail += "Không có thực đơn để thêm. ";
            }
            if (giagiam < 0 || giagiam > 100)
            {
                ViewBag.MessageFail += "% Khuyến mại không hợp lệ. ";
            }
            if (!string.IsNullOrEmpty(ViewBag.MessageFail))
            {
                return View();
            }

            KhuyenMai khuyenMai = new KhuyenMai();
            khuyenMai.ID_MonAn = monan;
            khuyenMai.GiamGia = giagiam;

            if (ModelState.IsValid)
            {
                data.KhuyenMais.InsertOnSubmit(khuyenMai);
                try
                {
                    data.SubmitChanges();
                }
                catch (Exception ex)
                {
                    if (ex.Message.Contains("Violation of PRIMARY KEY constraint"))
                    {
                        ViewBag.MessageFail = string.Format("Đã tồn tại khuyến mại cho thực đơn {0}.", khuyenMai.MONAN.TenMonAn);
                    }
                    else
                    {
                        ViewBag.ErrorBody = ex.ToString();
                    }
                    return View();
                }
            }
            ViewBag.MessageSuccess = "Thêm khuyến mại: [" + khuyenMai.MONAN.TenMonAn + "] thành công";
            return View();
        }

        // GET: AdminKhuyenMai/Edit/5
        public ActionResult Edit(int? id)
        {
            
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            KhuyenMai khuyenMai = data.KhuyenMais.SingleOrDefault(i => i.ID_MonAn == id);
            return View(khuyenMai);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormCollection form)
        {
            int idThucDon = Convert.ToInt32(form["IDThucDon"]);
            double giamGia = Convert.ToDouble(form["GiamGia"]);

            KhuyenMai km = data.KhuyenMais.SingleOrDefault(i => i.ID_MonAn == idThucDon);

            ViewBag.MessageFail = string.Empty;
            if (idThucDon == 0)
            {
                ViewBag.MessageFail += "Không có thực đơn để thêm. ";
            }
            if (giamGia < 0 || giamGia > 100)
            {
                ViewBag.MessageFail += "% Khuyến mại không hợp lệ. ";
            }
            if (!string.IsNullOrEmpty(ViewBag.MessageFail))
            {
                return View(km);
            }

            if (ModelState.IsValid)
            {
                UpdateModel(km);
                try
                {
                    data.SubmitChanges();
                }
                catch (Exception ex)
                {
                    if (ex.Message.Contains("Violation of PRIMARY KEY constraint"))
                    {
                        ViewBag.MessageFail = string.Format("Đã tồn tại khuyến mại cho thực đơn {0}.", km.MONAN.TenMonAn);
                    }
                    else
                    {
                        ViewBag.ErrorBody = ex.ToString();
                    }
                    return View();
                }
            }

            ViewBag.MessageSuccess = "Đã thay đổi thông tin khuyến mại cho [" + km.MONAN.TenMonAn + "] thành công";
            return RedirectToAction("Index");
        }

        // GET: AdminKhuyenMai/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            KhuyenMai km = data.KhuyenMais.SingleOrDefault(n => n.ID_MonAn == id);
            ViewBag.ID = km.ID_MonAn;
            if (km == null)
            {

                return RedirectToAction("Index", "AdminVIP");
            }
            return View(km);
        }

        // POST: AdminKhuyenMai/Delete/5
        [HttpPost]
        public ActionResult Delete(int id,FormCollection collection)
        {
            
            KhuyenMai km = data.KhuyenMais.SingleOrDefault(i => i.ID_MonAn == id);        
            /*if (countMonAn > 0)
            {
                ViewBag.ErrorBody = string.Format("Không thể Xóa,  do mã khuyến mại[{0}] đang áp dụng cho [{1}] món ăn.", km.ID_KhuyenMai, countMonAn);
                List<KHUYENMAI> all = data.KHUYENMAIs.ToList();
                return View("Index", all.ToList());
            }
            else*/
            if (ModelState.IsValid)
            {
                data.KhuyenMais.DeleteOnSubmit(km);
                data.SubmitChanges();
            }
            return RedirectToAction("Index");
        }
        [ChildActionOnly]
        public ActionResult PV_Dropdown_MonAn(int? id)
        {
            List<MONAN> all = data.MONANs.OrderBy(i => i.TenMonAn).ToList();
            if (id != null)
            {
                ViewBag.idLoai = id;
            }
            return PartialView(all);
        }
        [HttpPost]
        public ActionResult ThucDonById(int? val)
        {
            if (val != null)
            {
                //Values are hard coded for demo. you may replae with values 
                // coming from your db/service based on the passed in value ( val.Value)
                int id = val.Value;
                MONAN thucDon = data.MONANs.SingleOrDefault(i => i.ID_MonAn == id);
                string donGia = Convert.ToDecimal(thucDon.GiaBan).ToString("N0") + "đ";
                return Json(new { Success = "true", Data = new { DonGia = donGia } });
            }
            return Json(new { Success = "false" });
        }

        [HttpPost]
        public ActionResult GetGiaKhuyenMai(int? idThucDon, int? val)
        {
            if (val != null && idThucDon != null)
            {
                //Values are hard coded for demo. you may replae with values 
                // coming from your db/service based on the passed in value ( val.Value)
                double percent = Convert.ToDouble(val.Value) / 100;
                int id = idThucDon.Value;
                MONAN thucDon = data.MONANs.SingleOrDefault(i => i.ID_MonAn == id);
                if (thucDon != null)
                {
                    decimal giaGiam = Convert.ToDecimal(thucDon.GiaBan) * Convert.ToDecimal(percent);
                    string giaKhuyenMai = (Convert.ToDecimal(thucDon.GiaBan) - giaGiam).ToString("N0") + "đ";
                    return Json(new { Success = "true", Data = new { GiaKhuyenMai = giaKhuyenMai } });
                }
                else
                {
                    return Json(new { Success = "false" });
                }

            }
            return Json(new { Success = "false" });
        }

    }
}

S_FOOD/Views/AdminKhuyenMai/Create.cshtml
@model S_FOOD.Models.KHUYENMAI

@{
    ViewBag.Title = "Thêm VIP";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="main-content center">
    <div class=" row">
        <div class="span12">
            <h4 class="title"><span class="text"><strong>THÔNG TIN</strong> KHUYẾN MẠI </span></h4>
            <form action="#" method="post" class="form-stacked">
                <fieldset>
                    <div class="control-group" style="margin-bottom:17px">
                        <label class="control-label">Mã khuyễn mại:</label>
                        <div class="controls">
                            <input type="text" maxlength="10" name="IDKhuyenMai" class="form-control form-control-static"  required autofocus>
                        </div>
                    </div>
                    <div class="control-group" style="margin-bottom:17px">
                        <label class="control-label">Món ăn:</label>
                        @Html.Action("PV_Dropdown_MonAn", "AdminKhuyenMai")
                    </div>
                    <div class="control-group" style="margin-bottom:17px">
                        <label class="control-label">Giá giảm:</label>
                        <div class="controls">
                            <input type="number" min="500" name="GiaGiam" class="form-control form-control-static"  required autofocus>
                        </div>
                    </div>
                    <hr>
                    <div class="actions">
                        <input tabindex="6" class="btn btn-warning" type="submit" value="Lưu">
                    </div>

                </fieldset>
            </form>
        </div>
    </div>
</section>


<div>
    <button class="btn btn-primary">@Html.ActionLink("Về trang chủ", "Index")</button>
</div>

S_FOOD/Views/AdminKhuyenMai/Delete.cshtml
@model S_FOOD.Models.KhuyenMai

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3 class="center" style="color:red">Bạn có chắc muốn xóa?</h3>
<div>
    <h4 class="center">THÔNG TIN KHUYẾN MẠI</h4>
    <hr />
    <table class="table table-bordered table-striped table-hover">
        <tr class="center">
            <th class="center">Mã khuyến mại</th>
            <td class="center">@Model.ID_KhuyenMai</td>
        </tr>
        <tr class="center">
            <th class="center">Món ăn</th>
            <td class="center">@Model.MONAN.TenMonAn</td>
        </tr>
        <tr class="center">
            <th class="center">Giá giảm</th>
            <td class="center">@Model.GiamGia</td>
        </tr>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color center">
            <input type="submit" value="Đồng ý xóa" class="btn btn-danger" />
            <button class="btn btn-primary">@Html.ActionLink("Về trang chủ", "Index")</button>
        </div>
    }
</div>

S_FOOD/Views/AdminKhuyenMai/Details.cshtml
@model S_FOOD.Models.KHUYENMAI
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div>
    <h4 class="center">THÔNG TIN CHI TIẾT KHUYẾN MẠI <a style="color:red">@Model.ID_KhuyenMai</a></h4>
    <hr />
    <table class="table table-bordered table-striped table-hover">
        <tr class="center">
            <th class="center">Mã khuyến mại</th>
            <td class="center">@Model.ID_KhuyenMai</td>
        </tr>

        <tr class="center">
            <th class="center">Món ăn</th>
            <td class="center">@Model.MONAN.TenMonAn</td>
        </tr>

        <tr class="center">
            <th class="center">Giá gốc</th>
            <td class="center">@Model.MONAN.GiaBan</td>
        </tr>

        <tr class="center">
            <th class="center">Giá giảm</th>
            <td class="center">@Model.GiamGia</td>
        </tr>

        <tr class="center">
            <th class="center">Giá đã giảm</th>
            <td class="center">@ViewBag.Gia</td>
        </tr>

    </table>

</div>
<p class="center">
    <button class="btn btn-success">@Html.ActionLink("Sửa", "Edit", new { id = Model.ID_KhuyenMai })</button>
    <button class="btn btn-primary"> @Html.ActionLink("Về trang chủ", "Index")</button>
</p>

S_FOOD/Views/AdminKhuyenMai/Edit.cshtml
@model S_FOOD.Models.KhuyenMai

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group center">
        <h4>CHỈNH SỬA THÔNG TIN KHUYẾN MẠI <a style="color:red">@Model.ID_MonAn</a></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_MonAn)

        <div class="form-group">
            <label class="control-label">Món ăn:</label>
            @Html.Action("PV_Dropdown_MonAn", "CTVKhuyenMai")
        </div>

        <div class="form-group">
            @Html.Label("Giá giảm:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiamGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiamGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-primary">@Html.ActionLink("Về trang chủ", "Index")</button>
</div>

S_FOOD/Views/AdminKhuyenMai/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCTV.cshtml";
}


@model IEnumerable<S_FOOD.Models.KHUYENMAI>
<p>
    <button class="btn btn-warning">@Html.ActionLink("Thêm mới", "Create")</button>
</p>
<table class="table table-bordered table-hover table-striped" style="vertical-align:middle">
    <thead style="background-color:orange">
        <tr>
            <th class="center">
                Tên món ăn
            </th>
            <th class="center">
                Giá giảm
            </th>
            <th class="center">
                CTV
            </th>
            <th class="center">Tùy chọn</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr class="center">
            <td style="vertical-align:middle" class="center">
                @Html.DisplayFor(modelItem => item.MONAN.TenMonAn)
            </td>
            <td style="vertical-align:middle" class="center">
                @Html.DisplayFor(modelItem => item.GiamGia)
            </td>
            <td style="vertical-align:middle" class="center">
                @Html.DisplayFor(modelItem => item.MONAN.CONGTACVIEN.HoTen)
            </td>

            <td style="vertical-align:middle" class="center">
                <button class="btn btn-success">@Html.ActionLink("Sửa", "Edit", new { id = item.ID_MonAn }) </button>
                <button class="btn btn-primary">@Html.ActionLink("Chi tiết", "Details", new { id = item.ID_MonAn }) </button>
                <button class="btn btn-danger">@Html.ActionLink("Xóa", "Delete", new { id = item.ID_MonAn })</button>
            </td>
        </tr>
    }

</table>
<h5 class="center text-error"> @ViewBag.ErrorBody</h5>
<h5 class="center text-error"> @ViewBag.ErrorKM</h5>

S_FOOD/Views/AdminKhuyenMai/PV_Dropdown_MonAn.cshtml
@using S_FOOD.Models
@model List<MONAN>

<select name="IDMonAn" class="form-control form-control-static col-md-10" style="width:500px" required>
    @foreach (MONAN item in Model)
    {
        if (item == ViewBag.idLoai)
        {
            <option value="@item.ID_MonAn" selected>@item.TenMonAn</option>
        }
        else
        {
            <option value="@item.ID_MonAn">@item.TenMonAn</option>
        }
    }
</select>