S_FOOD/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace S_FOOD.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            if (Session["TenTK_Admin"] == null)
            {
                return RedirectToAction("DangNhap", "AdminTaiKhoan");
            }
            return View();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

S_FOOD/Controllers/CTVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;

namespace S_FOOD.Controllers
{
    public class CTVController : Controller
    {
        // GET: CTV
        public ActionResult Index()
        {
            if (Session["TenTK_CTV"] == null)
            {
                return RedirectToAction("DangNhap", "CTVTaiKhoan");
            }
            return View();
        }

        // GET: CTV/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CTV/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CTV/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CTV/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CTV/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CTV/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CTV/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

S_FOOD/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using S_FOOD.Models;
using PagedList.Mvc;
using PagedList;

namespace S_FOOD.Controllers
{
    public class TimKiemController : Controller
    {
        // GET: TimKiem
        private DBSfoodDataContext data = new DBSfoodDataContext();
        [HttpPost]
        public ActionResult KetQuaTimKiem(int? page, FormCollection f)
        {
            if (string.IsNullOrWhiteSpace(f["txtTimkiem"]))
            {
                return RedirectToAction("Index", "Home");
            }
            string tukhoa = f["txtTimkiem"].ToString();
            ViewBag.TK = tukhoa;
            List<MONAN> lsKQTK = data.MONANs.Where(n => n.TenMonAn.Contains(tukhoa)).ToList();
            int pageSize = 8;
            int pageNum = (page ?? 1);
            if (lsKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy";
                return View(data.MONANs.OrderBy(n => n.TenMonAn).ToPagedList(pageNum, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy" + " " + lsKQTK.Count + " " + "kết quả";
            return View(lsKQTK.OrderBy(n => n.TenMonAn).ToPagedList(pageNum, pageSize));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem()
        {
            return RedirectToAction("Index", "Sfood");
        }
    }
}

S_FOOD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

S_FOOD/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>Sfood - Admin | @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <!--[if ie]><meta content='IE=8' http-equiv='X-UA-Compatible'/><![endif]-->
    <!-- bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrappage.css" rel="stylesheet" />
    <!-- global styles -->
    <link href="~/Content/flexslider.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <!-- scripts -->
    <script src="~/Scripts/jquery-1.7.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/superfish.js"></script>
    <script src="~/Scripts/jquery.scrolltotop.js"></script>
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/Admin/favicon-32x32.png">

    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper" class="container">
        <section class="navbar main-menu">
            <div class="navbar-inner main-menu">
                <a href="@Url.Action("Index","Admin")" class="logo pull-left"><img src="~/images/LogoBanner/logo-sfood.png" style="height:55px; width:193px" alt=""></a>
                <nav id="menu" class="pull-right">
                    <ul>
                        <li><a href="@Url.Action("Index","Admin")">Trang chủ</a></li>
                        <li> @Html.Action("TaiKhoan", "AdminTaiKhoan")</li>
                    </ul>
                   
                </nav>
            </div>
        </section>
        <br />
         <br />

        @RenderBody()
        <section id="footer-bar">
            <div class="row">

            </div>
        </section>
        <section id="copyright">
            <span> <p>&copy; @DateTime.Now.Year - Đồ án cơ sở - Nguyễn Phước Phú</p></span>
        </section>
    </div>
    <script src="~/Scripts/common.js"></script>
    <script src="~/Scripts/jquery.flexslider-min.js"></script>
    <script type="text/javascript">
                                        $(function () {
                                            $(document).ready(function () {
                                                $('.flexslider').flexslider({
                                                    animation: "fade",
                                                    slideshowSpeed: 4000000,
                                                    animationSpeed: 60000,
                                                    controlNav: false,
                                                    directionNav: true,
                                                    controlsContainer: ".flex-container" // the container that holds the flexslider
                                                });
                                            });
                                        });
    </script>
</body>
</html>

S_FOOD/Views/Shared/_LayoutCTV.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>Sfood - CTV | @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <!--[if ie]><meta content='IE=8' http-equiv='X-UA-Compatible'/><![endif]-->
    <!-- bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrappage.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <!-- global styles -->
    <link href="~/Content/flexslider.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <!-- scripts -->
    <script src="~/Scripts/jquery-1.7.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/superfish.js"></script>
    <script src="~/Scripts/jquery.scrolltotop.js"></script>
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/Admin/favicon-32x32.png">


    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper" class="container">
        <section class="navbar main-menu">
            <div class="navbar-inner main-menu">
                <a href="@Url.Action("Index","CTV")" class="logo pull-left"><img src="~/images/LogoBanner/logo-sfood.png" style="height:55px; width:193px" alt=""></a>
                <nav id="menu" class="pull-right">
                    <ul>
                        <li><a href=" @Url.Action("Index","CTV")">Trang chủ</a></li>
                        <li> @Html.Action("TaiKhoan", "CTVTaiKhoan")</li>
                    </ul>
                </nav>
            </div>
        </section>
        <br />      
           @RenderBody()
                                           <section id="footer-bar">
                                                <div class="row">
                                                    
                                                </div>
                                            </section>
                                            <section id="copyright">
                                                <span> <p>&copy; @DateTime.Now.Year - Đồ án cơ sở - Nguyễn Phước Phú</p></span>
                                            </section>
                                    </div>
                                    <script src="~/Scripts/common.js"></script>
                                    <script src="~/Scripts/jquery.flexslider-min.js"></script>
                                    <script type="text/javascript">
                                        $(function () {
                                            $(document).ready(function () {
                                                $('.flexslider').flexslider({
                                                    animation: "fade",
                                                    slideshowSpeed: 4000,
                                                    animationSpeed: 600,
                                                    controlNav: false,
                                                    directionNav: true,
                                                    controlsContainer: ".flex-container" // the container that holds the flexslider
                                                });
                                            });
                                        });
                                    </script>
</body>
</html>

S_FOOD/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>Sfood-@ViewBag.Title </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <!--[if ie]><meta content='IE=8' http-equiv='X-UA-Compatible'/><![endif]-->
    <!-- bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrappage.css" rel="stylesheet" />
    <!-- global styles -->
    <link href="~/Content/flexslider.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <!-- scripts -->
    <script src="~/Scripts/jquery-1.7.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/superfish.js"></script>
    <script src="~/Scripts/jquery.scrolltotop.js"></script>
    <link rel="icon" type="image/png" sizes="40x40" href="~/images/Admin/favicon-32x32.png">



    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    @*plugin facebook*@
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.0&appId=213159655944732&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    @*-------------------------*@
    <div id="top-bar" class="container">
        <div class="row">
            <div class="span4">
                @using (Html.BeginForm("KetQuaTimKiem", "TimKiem", FormMethod.Post, new { @class = "form-inline" }))
                {
                    <form method="POST" class="search_form">
                        <input type="text" name="txtTimkiem" class="input-block-level search-query " Placeholder="Bạn tìm gì?..." />
                    </form>
                }
            </div>
            <div class="span8">
                <div class="account pull-right">
                    <ul class="user-menu">
                        @Html.Action("GiohangPartial", "GioHang")
                        @Html.Action("TaiKhoan", "NguoiDung")
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="wrapper" class="container">
        @Html.Action("PV_Header", "AdminCaiDat")
        <br />

        @RenderBody()

        <section id="footer-bar">
            @*Zalo chat*@
            <div class="zalo-chat-widget" data-oaid="3021233795120822301" data-welcome-message="Rất vui khi được hỗ trợ bạn!" data-autopopup="0" data-width="350" data-height="420"></div>

            <script src="https://sp.zalo.me/plugins/sdk.js"></script>
            <div class="row">
                <div class="span3">
                    <h4>Liên kết</h4>
                    <ul class="nav">
                        <li><a href="@Url.Action("Index","Sfood")">Trang chủ</a></li>
                        <li><a href="@Url.Action("About","Sfood")">About</a></li>                        
                        <li><a href="@Url.Action("DangNhap","NguoiDung")">Đăng nhập</a></li>
                    </ul>
                </div>
                <div class="span4">
                    <h4>Tài khoản của tôi</h4>
                    <ul class="nav">
                        <li><a href="@Url.Action("ThongTinTK","NguoiDung")">Thông tin tài khoản</a></li>
                        <li><a href="@Url.Action("LichSuMuaHang","GioHang")">Lịch sử mua hàng</a></li>
                        <li><a href="@Url.Action("DangKy","NguoiDung")">Đăng ký</a></li>                     
                    </ul>
                </div>
                <div class="span5">
                    <p class="logo"><img src="~/images/LogoBanner/logo-sfood.png" class="site_logo" alt=""></p>
                    <p>Địa chỉ: 475A, Điện Biên Phủ, P.25, Q.Bình Thạnh, Tp.HCM</p>
                    <p>Email: npphu97@gmail.com</p>
                    <p>Hotline: 01289584139</p>
                    <br />
                </div>
            </div>
        </section>
        <section id="copyright">
            <span> <p>&copy; @DateTime.Now.Year - Đồ án cơ sở - Nguyễn Phước Phú</p></span>
        </section>
    </div>
    <script src="~/Scripts/common.js"></script>
    <script src="~/Scripts/jquery.flexslider-min.js"></script>
    <script type="text/javascript">
        $(function () {
            $(document).ready(function () {
                $('.flexslider').flexslider({
                    animation: "fade",
                    slideshowSpeed: 4000,
                    animationSpeed: 600,
                    controlNav: false,
                    directionNav: true,
                    controlsContainer: ".flex-container" // the container that holds the flexslider
                });
            });
        });
    </script>
    <script src="https://sp.zalo.me/plugins/sdk.js"></script>
</body>
</html>